# Provisioning is offline. Paths and digests must come from a separately reviewed lock.
function(documents_verified_file name)
  if(NOT DEFINED ${name} OR NOT EXISTS "${${name}}" OR IS_DIRECTORY "${${name}}")
    message(FATAL_ERROR "Required local file: ${name}")
  endif()
  if(NOT DEFINED ${name}_SHA256)
    message(FATAL_ERROR "Required approved digest: ${name}_SHA256")
  endif()
  string(LENGTH "${${name}_SHA256}" digest_length)
  if(NOT digest_length EQUAL 64 OR NOT "${${name}_SHA256}" MATCHES "^[0-9a-fA-F]+$")
    message(FATAL_ERROR "Invalid SHA-256 for ${name}")
  endif()
  file(SHA256 "${${name}}" actual)
  string(TOLOWER "${${name}_SHA256}" expected)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Digest mismatch: ${name}")
  endif()
endfunction()

foreach(name DOCUMENTS_PDFIUM_LIBRARY DOCUMENTS_TESSERACT_LIBRARY
    DOCUMENTS_LEPTONICA_LIBRARY DOCUMENTS_PNG_LIBRARY DOCUMENTS_JPEG_LIBRARY
    DOCUMENTS_ZLIB_LIBRARY DOCUMENTS_ENG_DATA DOCUMENTS_RUS_DATA
    DOCUMENTS_PROVISIONING_MANIFEST DOCUMENTS_LICENSES)
  documents_verified_file(${name})
endforeach()
foreach(name DOCUMENTS_PDFIUM_INCLUDE DOCUMENTS_TESSERACT_INCLUDE DOCUMENTS_LEPTONICA_INCLUDE)
  if(NOT IS_DIRECTORY "${${name}}")
    message(FATAL_ERROR "Required provisioned include directory: ${name}")
  endif()
endforeach()
if(NOT DOCUMENTS_PROVISIONING_REVIEWED)
  message(FATAL_ERROR "Externally verify source/header/codec hashes, versions and PDFium no-V8/no-XFA provenance first")
endif()
foreach(dependency PDFIUM TESSERACT LEPTONICA PNG JPEG ZLIB)
  add_library(documents_${dependency} UNKNOWN IMPORTED)
  set_target_properties(documents_${dependency} PROPERTIES
    IMPORTED_LOCATION "${DOCUMENTS_${dependency}_LIBRARY}")
  if(dependency MATCHES "^(PDFIUM|TESSERACT|LEPTONICA)$")
    set_target_properties(documents_${dependency} PROPERTIES
      INTERFACE_INCLUDE_DIRECTORIES "${DOCUMENTS_${dependency}_INCLUDE}")
  endif()
endforeach()
set_property(TARGET documents_TESSERACT PROPERTY INTERFACE_LINK_LIBRARIES documents_LEPTONICA)
set_property(TARGET documents_TESSERACT PROPERTY INTERFACE_COMPILE_DEFINITIONS TESS_STATIC)
set_property(TARGET documents_LEPTONICA PROPERTY INTERFACE_LINK_LIBRARIES
  "documents_PNG;documents_JPEG;documents_ZLIB")
set_property(TARGET documents_LEPTONICA PROPERTY INTERFACE_COMPILE_DEFINITIONS LIBLEPT_STATIC)
set_property(TARGET documents_PNG PROPERTY INTERFACE_LINK_LIBRARIES documents_ZLIB)
if(ANDROID)
  add_subdirectory(android_cpu_features)
  set_property(TARGET documents_TESSERACT APPEND PROPERTY INTERFACE_LINK_LIBRARIES
    "CpuFeatures::ndk_compat;log;m")
endif()
