cmake_minimum_required(VERSION 3.22)

function(require_file name)
  if(NOT IS_ABSOLUTE "${${name}}" OR NOT EXISTS "${${name}}" OR
      IS_DIRECTORY "${${name}}" OR IS_SYMLINK "${${name}}")
    message(FATAL_ERROR "${name} must name an existing absolute local regular file")
  endif()
endfunction()

function(check_hash path expected)
  string(LENGTH "${expected}" length)
  if(NOT length EQUAL 64 OR NOT expected MATCHES "^[0-9a-fA-F]+$")
    message(FATAL_ERROR "Required prior SHA-256 for ${path}")
  endif()
  file(SHA256 "${path}" actual)
  string(TOLOWER "${expected}" expected)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Prior SHA-256 mismatch: ${path}")
  endif()
endfunction()

function(cache_value name value)
  # Quote arbitrary local paths without allowing CMake code interpolation.
  set(equals "=")
  while("${value}" MATCHES "]${equals}]")
    string(APPEND equals "=")
  endwhile()
  set(config "${config}set(${name} [${equals}[${value}]${equals}] CACHE STRING \"Local build identity\" FORCE)\n" PARENT_SCOPE)
endfunction()

function(record_file label path)
  file(SHA256 "${path}" digest)
  string(APPEND identity "${digest}  ${label}  ${path}\n")
  set(identity "${identity}" PARENT_SCOPE)
endfunction()

function(record_tree name)
  if(NOT IS_ABSOLUTE "${${name}}" OR NOT IS_DIRECTORY "${${name}}" OR
      IS_SYMLINK "${${name}}")
    message(FATAL_ERROR "Required absolute local tree: ${name}")
  endif()
  file(GLOB_RECURSE entries LIST_DIRECTORIES true RELATIVE "${${name}}" "${${name}}/*")
  list(SORT entries)
  set(tree_identity "")
  set(count 0)
  foreach(entry IN LISTS entries)
    set(path "${${name}}/${entry}")
    if(IS_SYMLINK "${path}")
      message(FATAL_ERROR "Symlink in identity tree: ${path}")
    endif()
    if(NOT IS_DIRECTORY "${path}")
      file(SHA256 "${path}" digest)
      string(APPEND tree_identity "${digest}  ${entry}\n")
      math(EXPR count "${count} + 1")
    endif()
  endforeach()
  if(count EQUAL 0)
    message(FATAL_ERROR "Empty identity tree: ${name}")
  endif()
  string(SHA256 tree_digest "${tree_identity}")
  string(APPEND identity "TREE ${name} ${${name}} SHA256 ${tree_digest}\n${tree_identity}")
  set(identity "${identity}" PARENT_SCOPE)
endfunction()

if(NOT IS_ABSOLUTE "${DOCUMENTS_TEMP_ROOT}" OR
    NOT IS_DIRECTORY "${DOCUMENTS_TEMP_ROOT}" OR
    NOT IS_ABSOLUTE "${DOCUMENTS_LOCAL_OUTPUT}")
  message(FATAL_ERROR "Supply an existing absolute DOCUMENTS_TEMP_ROOT and absolute DOCUMENTS_LOCAL_OUTPUT")
endif()
file(REAL_PATH "${DOCUMENTS_TEMP_ROOT}" temp_root)
file(REAL_PATH "${CMAKE_CURRENT_LIST_DIR}/../.." repository)
cmake_path(IS_PREFIX repository "${temp_root}" NORMALIZE in_repository)
if(in_repository)
  message(FATAL_ERROR "Temporary output must be outside the application repository")
endif()
get_filename_component(output_parent "${DOCUMENTS_LOCAL_OUTPUT}" DIRECTORY)
get_filename_component(output_name "${DOCUMENTS_LOCAL_OUTPUT}" NAME)
file(REAL_PATH "${output_parent}" output_parent)
if(NOT output_parent STREQUAL temp_root OR NOT output_name MATCHES "^[A-Za-z0-9_-]+$")
  message(FATAL_ERROR "Output must be a named direct child of DOCUMENTS_TEMP_ROOT")
endif()
set(output "${temp_root}/${output_name}")
if(EXISTS "${output}" OR IS_SYMLINK "${output}")
  message(FATAL_ERROR "Refusing to overwrite existing output: ${output}")
endif()

require_file(DOCUMENTS_PRIOR_ARCHIVE_MANIFEST)
check_hash("${DOCUMENTS_PRIOR_ARCHIVE_MANIFEST}" "${DOCUMENTS_PRIOR_ARCHIVE_MANIFEST_SHA256}")
file(READ "${DOCUMENTS_PRIOR_ARCHIVE_MANIFEST}" prior)
set(identity "mobilka local build identity v1\nLOCAL ONLY: measured bytes, not official source/archive provenance verification.\n")
record_file(PRIOR_ARCHIVE_MANIFEST "${DOCUMENTS_PRIOR_ARCHIVE_MANIFEST}")
foreach(dep PDFIUM TESSERACT LEPTONICA PNG JPEG ZLIB ENG RUS)
  require_file(DOCUMENTS_${dep}_ARCHIVE)
  string(JSON expected GET "${prior}" archives ${dep} sha256)
  check_hash("${DOCUMENTS_${dep}_ARCHIVE}" "${expected}")
  record_file("PRIOR_HASH_MATCH_${dep}" "${DOCUMENTS_${dep}_ARCHIVE}")
endforeach()
require_file(DOCUMENTS_BUILD_IDENTITY)
record_file(BUILD_IDENTITY "${DOCUMENTS_BUILD_IDENTITY}")
file(READ "${DOCUMENTS_BUILD_IDENTITY}" build_identity)
string(APPEND identity "BUILD METADATA (caller supplied, local only)\n${build_identity}\n")
set(config "# Measured local identity only; external provenance review is still required.\n")
foreach(dep PDFIUM TESSERACT LEPTONICA PNG JPEG ZLIB)
  set(name DOCUMENTS_${dep}_LIBRARY)
  require_file(${name})
  record_file(${name} "${${name}}")
  file(SHA256 "${${name}}" digest)
  cache_value(${name} "${${name}}")
  cache_value(${name}_SHA256 "${digest}")
  record_tree(DOCUMENTS_${dep}_INCLUDE)
  cache_value(DOCUMENTS_${dep}_INCLUDE "${DOCUMENTS_${dep}_INCLUDE}")
  if(NOT dep STREQUAL "PDFIUM")
    record_tree(DOCUMENTS_${dep}_SOURCE)
  endif()
endforeach()
foreach(lang ENG RUS)
  set(name DOCUMENTS_${lang}_DATA)
  require_file(${name})
  record_file(${name} "${${name}}")
  file(SHA256 "${${name}}" digest)
  cache_value(${name} "${${name}}")
  cache_value(${name}_SHA256 "${digest}")
endforeach()
foreach(runtime IN LISTS DOCUMENTS_RUNTIME_FILES)
  require_file(runtime)
  record_file(RUNTIME "${runtime}")
endforeach()

set(notices "")
foreach(dep PDFIUM PDFIUM_DEPENDENCY TESSERACT LEPTONICA PNG JPEG ZLIB ENG RUS)
  set(name DOCUMENTS_${dep}_LICENSE_FILES)
  if("${${name}}" STREQUAL "")
    message(FATAL_ERROR "Supply complete existing license/notice files: ${name}")
  endif()
  foreach(license IN LISTS ${name})
    require_file(license)
    file(SIZE "${license}" size)
    if(size EQUAL 0)
      message(FATAL_ERROR "Empty license: ${license}")
    endif()
    record_file("LICENSE_${dep}" "${license}")
    file(READ "${license}" contents)
    string(APPEND notices "\n===== ${dep}: ${license} =====\n${contents}\n")
  endforeach()
endforeach()

# All inputs have passed validation before any output is created.
file(MAKE_DIRECTORY "${output}")
file(WRITE "${output}/local-build-identity.txt" "${identity}")
file(WRITE "${output}/LICENSES.txt" "${notices}")
file(COPY_FILE "${DOCUMENTS_PRIOR_ARCHIVE_MANIFEST}" "${output}/prior-archive-manifest.json")
set(DOCUMENTS_PROVISIONING_MANIFEST "${output}/local-build-identity.txt")
set(DOCUMENTS_LICENSES "${output}/LICENSES.txt")
foreach(name DOCUMENTS_PROVISIONING_MANIFEST DOCUMENTS_LICENSES)
  file(SHA256 "${${name}}" digest)
  cache_value(${name} "${${name}}")
  cache_value(${name}_SHA256 "${digest}")
endforeach()
cache_value(DOCUMENTS_PROVISIONING_REVIEWED OFF)
file(WRITE "${output}/local-config.cmake" "${config}")
message(STATUS "Local identity only: ${output}/local-config.cmake; external review gate remains OFF")
