#ifndef MOBILKA_NDK_COMPAT_CPU_FEATURES_H_
#define MOBILKA_NDK_COMPAT_CPU_FEATURES_H_

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum AndroidCpuFamily {
  ANDROID_CPU_FAMILY_UNKNOWN = 0,
  ANDROID_CPU_FAMILY_ARM = 1,
  ANDROID_CPU_FAMILY_X86 = 2,
  ANDROID_CPU_FAMILY_MIPS = 3,
  ANDROID_CPU_FAMILY_ARM64 = 4,
  ANDROID_CPU_FAMILY_X86_64 = 5,
  ANDROID_CPU_FAMILY_MIPS64 = 6,
} AndroidCpuFamily;

enum {
  ANDROID_CPU_ARM_FEATURE_ARMv7 = (1ULL << 0),
  ANDROID_CPU_ARM_FEATURE_VFPv3 = (1ULL << 1),
  ANDROID_CPU_ARM_FEATURE_NEON = (1ULL << 2),
  ANDROID_CPU_ARM_FEATURE_LDREX_STREX = (1ULL << 3),
  ANDROID_CPU_ARM_FEATURE_VFPv2 = (1ULL << 4),
  ANDROID_CPU_ARM_FEATURE_VFP_D32 = (1ULL << 5),
  ANDROID_CPU_ARM_FEATURE_VFP_FP16 = (1ULL << 6),
  ANDROID_CPU_ARM_FEATURE_VFP_FMA = (1ULL << 7),
  ANDROID_CPU_ARM_FEATURE_NEON_FMA = (1ULL << 8),
  ANDROID_CPU_ARM_FEATURE_IDIV_ARM = (1ULL << 9),
  ANDROID_CPU_ARM_FEATURE_IDIV_THUMB2 = (1ULL << 10),
  ANDROID_CPU_ARM_FEATURE_iWMMXt = (1ULL << 11),
  ANDROID_CPU_ARM_FEATURE_AES = (1ULL << 12),
  ANDROID_CPU_ARM_FEATURE_PMULL = (1ULL << 13),
  ANDROID_CPU_ARM_FEATURE_SHA1 = (1ULL << 14),
  ANDROID_CPU_ARM_FEATURE_SHA2 = (1ULL << 15),
  ANDROID_CPU_ARM_FEATURE_CRC32 = (1ULL << 16),
};

AndroidCpuFamily android_getCpuFamily(void);
uint64_t android_getCpuFeatures(void);

#ifdef __cplusplus
}
#endif

#endif
